lib/takso_web/router.ex
defmodule TaksoWeb.Router do
  use TaksoWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

	pipeline :with_session do
	  plug Guardian.Plug.VerifySession
	  plug Guardian.Plug.LoadResource
	  plug TaksoWeb.CurrentUser
  end

  pipeline :taxi_required do
    plug TaksoWeb.CheckTaxi
  end

  pipeline :operator_required do
    plug TaksoWeb.CheckOperator
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", TaksoWeb do
    pipe_through [:browser, :with_session]

    get "/", PageController, :index
    resources "/users", UserController, only: [:show, :new, :create]
    resources "/sessions", SessionController, only: [:new, :create, :delete, :show]

    scope "/orders" do
      get "/accept", OrderController, :accept
      get "/cancel", OrderController, :cancel
      get "/:id", OrderController, :user_show
    end

    scope "/apply" do
      resources "/", ApplyController, only: [:new, :create, :delete, :show]
      post "/update", ApplyController, :update_status
    end

    scope "/taxi" do
      pipe_through [:taxi_required]

      resources "/orders", OrderController, only: [:index, :update]
      get "/history", OrderController, :history
      post "/action", OrderController, :action_update
      get "/active", OrderController, :active
      post "/finish", OrderController, :finish
      resources "/", TaxiController, only: [:index, :new]

    end

    scope "/operator" do
      pipe_through [:operator_required]

      resources "/", OperatorController, only: [:index, :edit, :update]
      get "/drivers", OperatorController, :drivers
      get "/orders", OperatorController, :orders
      get "/applications", OperatorController, :applications
    end
  end

  scope "/client", TaksoWeb do
    pipe_through [:api]

    post "/orders", OrderController, :create
  end
end

lib/takso_web/views/layout_view.ex
defmodule TaksoWeb.LayoutView do
  use TaksoWeb, :view
end

lib/takso_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Strelsau Taxi</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">

    <style>
    body, html {
      height: 100%;
      margin: 0;
    }

    .bg {
      background-image: url("/images/taxi.jpg");
      height: 100%; 
      background-position: center;
      background-repeat: repeat-y;
      background-size: cover;
    }
    </style>
  </head>

  <body class="bg">
      <header class="header">
            
        <nav class="navbar navbar-expand-sm bg-light justify-content-end">
        <a style="background-color: black;" class="navbar-brand" href="#">
          <img src="<%= static_path(@conn, "/images/StrelsauTaxi.png") %>">
        </a>
          <ul class="navbar-nav">
            <%= if @current_user do %>
            <span class="navbar-text"><b>Hello, <%= @current_user.name %></b></span>
              <li class="nav-item"><%= link "Sign out", to: session_path(@conn, :delete, @current_user), method: :delete, class: "nav-link" %></li>
              <%= if Plug.Conn.get_session(@conn, :login) == "Driver" do %>
                <li class="nav-item"><%= link "Show history", to: order_path(@conn, :history), class: "nav-link"  %></li>
                <li class="nav-item"><%= link "Show orders", to: order_path(@conn, :index), class: "nav-link"  %></li>
				      <% else %>
                <li class="nav-item"><%= link "Apply for a taxi driver", to: apply_path(@conn, :new), class: "nav-link"  %></li>
              <% end %>
            <% else %>
              <li class="nav-item"><%= link "Register", to: user_path(@conn, :new), class: "nav-link"  %></li>
              <li class="nav-item"><%= link "Sign in", to: session_path(@conn, :new), class: "nav-link"  %></li>
            <% end %>
          </ul>
        </nav>
      </header>
      <div class="container">

      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>

      <main role="main">
        <div class="container">
          <%= render @view_module, @view_template, assigns %>
        </div>
      </main>

    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>